// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxInk0StkatHHjKC6W6KjI0GUlV3bNaAA',
    appId: '1:140032564417:web:7e50cfaf2400e49cf80840',
    messagingSenderId: '140032564417',
    projectId: 'bookexchangesystem-90aba',
    authDomain: 'bookexchangesystem-90aba.firebaseapp.com',
    storageBucket: 'bookexchangesystem-90aba.appspot.com',
    measurementId: 'G-GK150PW4FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH3SLWVbR_xtOz8ERm1kKaNRIE0AvO_1A',
    appId: '1:140032564417:android:72aa3c4104a05f3bf80840',
    messagingSenderId: '140032564417',
    projectId: 'bookexchangesystem-90aba',
    storageBucket: 'bookexchangesystem-90aba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqm9Jcfq17mpmvmfg2s6sCPx8xXoD4eMc',
    appId: '1:140032564417:ios:02da819dc9083cfef80840',
    messagingSenderId: '140032564417',
    projectId: 'bookexchangesystem-90aba',
    storageBucket: 'bookexchangesystem-90aba.appspot.com',
    iosClientId: '140032564417-3qj031k6lrnrmo9bg1tgb95elnkrndp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookExchangeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqm9Jcfq17mpmvmfg2s6sCPx8xXoD4eMc',
    appId: '1:140032564417:ios:02da819dc9083cfef80840',
    messagingSenderId: '140032564417',
    projectId: 'bookexchangesystem-90aba',
    storageBucket: 'bookexchangesystem-90aba.appspot.com',
    iosClientId: '140032564417-3qj031k6lrnrmo9bg1tgb95elnkrndp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookExchangeAdmin',
  );
}
